### ISSUE TITLE
Migrate to Python 3 (2.7 end of life)

### ISSUE THREAD

**Issue by ergoithz** [migasfree/migasfree#283]
Starting a project with 2.7 when 3 is being out there for quite long (now it's older than a decade) isn't a clever idea, furthermore when a ton of tools provide an easier way to either migrate codebase over, or just make a project both forward and backwards compatible.

But nowadays this situation is way worse: Python 2.7 is approaching its end of life (see https://legacy.python.org/dev/peps/pep-0373/ ), so it's time to face this project has to choose between being updated or becoming unusable pretty soon (due lack of support and security updates).

This issue is here to point that: as this project has become so useful for so many people, its fall due lack of foresight would be a bummer.

**Comment by jact** [comment]
Nothing we would like more than working with Python 3, Django 2 and other component upgrades.

However, because there are discontinued project dependencies, it is not possible for us to update Python or Django, without making major structural changes to the project.

Anyway, we have in mind carry out those changes and, in a while, start using Python 3.

Thank you.
